-- =============================================================================
-- Refex Mobility — Vehicle asset profile (fleet identity, EV, legal, org, finance)
-- Vehicle-only model (not multi-purpose asset engine).
-- =============================================================================

ALTER TABLE `vehicles`
  ADD COLUMN `fleet_id` VARCHAR(64) NULL AFTER `vehicle_number`,
  ADD COLUMN `vehicle_type` VARCHAR(64) NULL DEFAULT 'Passenger Car' AFTER `category`,
  ADD COLUMN `vehicle_sub_type` VARCHAR(64) NULL AFTER `vehicle_type`,
  ADD COLUMN `make` VARCHAR(100) NULL AFTER `model`,
  ADD COLUMN `variant` VARCHAR(100) NULL AFTER `make`,
  ADD COLUMN `model_year` SMALLINT UNSIGNED NULL AFTER `variant`,
  ADD COLUMN `color` VARCHAR(64) NULL AFTER `model_year`,
  ADD COLUMN `primary_image_path` VARCHAR(512) NULL AFTER `color`,
  ADD COLUMN `seats` TINYINT UNSIGNED NULL AFTER `primary_image_path`,
  ADD COLUMN `description` TEXT NULL AFTER `notes`,

  ADD COLUMN `vin` VARCHAR(64) NULL AFTER `description`,
  ADD COLUMN `chassis_number` VARCHAR(64) NULL AFTER `vin`,
  ADD COLUMN `engine_number` VARCHAR(64) NULL AFTER `chassis_number`,
  ADD COLUMN `motor_number` VARCHAR(64) NULL AFTER `engine_number`,
  ADD COLUMN `battery_serial_number` VARCHAR(64) NULL AFTER `motor_number`,
  ADD COLUMN `vehicle_id_number` VARCHAR(64) NULL AFTER `battery_serial_number`,
  ADD COLUMN `key_id` VARCHAR(64) NULL AFTER `vehicle_id_number`,
  ADD COLUMN `rfid_tag` VARCHAR(64) NULL AFTER `key_id`,
  ADD COLUMN `barcode` VARCHAR(64) NULL AFTER `rfid_tag`,
  ADD COLUMN `registration_date` DATE NULL AFTER `barcode`,
  ADD COLUMN `registration_state` VARCHAR(64) NULL AFTER `registration_date`,
  ADD COLUMN `registration_rto` VARCHAR(100) NULL AFTER `registration_state`,
  ADD COLUMN `registration_expiry` DATE NULL AFTER `registration_rto`,
  ADD COLUMN `vehicle_class` VARCHAR(64) NULL AFTER `registration_expiry`,
  ADD COLUMN `puc_number` VARCHAR(100) NULL AFTER `vehicle_class`,
  ADD COLUMN `puc_issue_date` DATE NULL AFTER `puc_number`,
  ADD COLUMN `puc_expiry_date` DATE NULL AFTER `puc_issue_date`,
  ADD COLUMN `fitness_number` VARCHAR(100) NULL AFTER `puc_expiry_date`,
  ADD COLUMN `fitness_expiry_date` DATE NULL AFTER `fitness_number`,
  ADD COLUMN `permit_number` VARCHAR(100) NULL AFTER `fitness_expiry_date`,
  ADD COLUMN `permit_expiry_date` DATE NULL AFTER `permit_number`,

  ADD COLUMN `powertrain_type` VARCHAR(64) NULL AFTER `fuel_type`,
  ADD COLUMN `battery_type` VARCHAR(64) NULL AFTER `powertrain_type`,
  ADD COLUMN `battery_capacity` DECIMAL(10,2) NULL AFTER `battery_type`,
  ADD COLUMN `battery_unit` VARCHAR(16) NULL DEFAULT 'kWh' AFTER `battery_capacity`,
  ADD COLUMN `usable_battery_capacity` DECIMAL(10,2) NULL AFTER `battery_unit`,
  ADD COLUMN `charging_types` VARCHAR(255) NULL AFTER `usable_battery_capacity`,
  ADD COLUMN `ac_charging_capacity` DECIMAL(10,2) NULL AFTER `charging_types`,
  ADD COLUMN `dc_fast_charging_capacity` DECIMAL(10,2) NULL AFTER `ac_charging_capacity`,
  ADD COLUMN `charging_connector_type` VARCHAR(64) NULL AFTER `dc_fast_charging_capacity`,
  ADD COLUMN `charging_port_count` TINYINT UNSIGNED NULL AFTER `charging_connector_type`,
  ADD COLUMN `range_value` DECIMAL(10,2) NULL AFTER `charging_port_count`,
  ADD COLUMN `range_unit` VARCHAR(16) NULL DEFAULT 'km' AFTER `range_value`,
  ADD COLUMN `battery_warranty_start` DATE NULL AFTER `range_unit`,
  ADD COLUMN `battery_warranty_end` DATE NULL AFTER `battery_warranty_start`,
  ADD COLUMN `battery_warranty_km` INT UNSIGNED NULL AFTER `battery_warranty_end`,
  ADD COLUMN `battery_health_pct` DECIMAL(5,2) NULL AFTER `battery_warranty_km`,
  ADD COLUMN `battery_cycle_count` INT UNSIGNED NULL AFTER `battery_health_pct`,
  ADD COLUMN `state_of_charge_pct` DECIMAL(5,2) NULL AFTER `battery_cycle_count`,
  ADD COLUMN `last_charging_at` DATETIME NULL AFTER `state_of_charge_pct`,
  ADD COLUMN `last_charging_location` VARCHAR(255) NULL AFTER `last_charging_at`,
  ADD COLUMN `charging_station_id` VARCHAR(64) NULL AFTER `last_charging_location`,
  ADD COLUMN `telematics_device_id` VARCHAR(64) NULL AFTER `charging_station_id`,

  ADD COLUMN `company_id` INT UNSIGNED NULL AFTER `city_id`,
  ADD COLUMN `legal_entity_id` INT UNSIGNED NULL AFTER `company_id`,
  ADD COLUMN `business_unit` VARCHAR(100) NULL AFTER `legal_entity_id`,
  ADD COLUMN `department_id` INT UNSIGNED NULL AFTER `business_unit`,
  ADD COLUMN `team_name` VARCHAR(100) NULL AFTER `department_id`,
  ADD COLUMN `cost_center` VARCHAR(64) NULL AFTER `team_name`,
  ADD COLUMN `sub_location` VARCHAR(100) NULL AFTER `cost_center`,
  ADD COLUMN `fleet_name` VARCHAR(100) NULL AFTER `sub_location`,
  ADD COLUMN `vehicle_pool` VARCHAR(100) NULL AFTER `fleet_name`,
  ADD COLUMN `vehicle_owner_id` INT UNSIGNED NULL AFTER `vehicle_pool`,
  ADD COLUMN `fleet_manager_id` INT UNSIGNED NULL AFTER `vehicle_owner_id`,
  ADD COLUMN `current_custodian_id` INT UNSIGNED NULL AFTER `fleet_manager_id`,
  ADD COLUMN `assignment_kind` VARCHAR(64) NULL AFTER `assigned_type`,
  ADD COLUMN `driver_name` VARCHAR(191) NULL AFTER `assignment_kind`,
  ADD COLUMN `driver_phone` VARCHAR(32) NULL AFTER `driver_name`,
  ADD COLUMN `assignment_status` VARCHAR(64) NULL AFTER `driver_phone`,
  ADD COLUMN `assignment_location` VARCHAR(100) NULL AFTER `assignment_status`,

  ADD COLUMN `location_type` VARCHAR(64) NULL AFTER `location_name`,
  ADD COLUMN `latitude` DECIMAL(10,7) NULL AFTER `location_type`,
  ADD COLUMN `longitude` DECIMAL(10,7) NULL AFTER `latitude`,
  ADD COLUMN `address` TEXT NULL AFTER `longitude`,
  ADD COLUMN `last_location_updated` DATETIME NULL AFTER `address`,
  ADD COLUMN `gps_accuracy_m` DECIMAL(10,2) NULL AFTER `last_location_updated`,
  ADD COLUMN `geofence_name` VARCHAR(100) NULL AFTER `gps_accuracy_m`,
  ADD COLUMN `parking_location` VARCHAR(191) NULL AFTER `geofence_name`,

  ADD COLUMN `procurement_type` VARCHAR(64) NULL AFTER `purchase_cost`,
  ADD COLUMN `invoice_number` VARCHAR(100) NULL AFTER `order_number`,
  ADD COLUMN `invoice_date` DATE NULL AFTER `invoice_number`,
  ADD COLUMN `vendor_name` VARCHAR(191) NULL AFTER `supplier_name`,
  ADD COLUMN `dealer_name` VARCHAR(191) NULL AFTER `vendor_name`,
  ADD COLUMN `tax_amount` DECIMAL(12,2) NULL AFTER `dealer_name`,
  ADD COLUMN `total_cost` DECIMAL(12,2) NULL AFTER `tax_amount`,
  ADD COLUMN `currency` VARCHAR(8) NULL DEFAULT 'INR' AFTER `total_cost`,
  ADD COLUMN `funding_type` VARCHAR(64) NULL AFTER `currency`,
  ADD COLUMN `financing_company` VARCHAR(191) NULL AFTER `funding_type`,
  ADD COLUMN `loan_number` VARCHAR(100) NULL AFTER `financing_company`,
  ADD COLUMN `loan_start_date` DATE NULL AFTER `loan_number`,
  ADD COLUMN `loan_end_date` DATE NULL AFTER `loan_start_date`,

  ADD COLUMN `asset_cost` DECIMAL(12,2) NULL AFTER `loan_end_date`,
  ADD COLUMN `capitalized_cost` DECIMAL(12,2) NULL AFTER `asset_cost`,
  ADD COLUMN `current_book_value` DECIMAL(12,2) NULL AFTER `capitalized_cost`,
  ADD COLUMN `depreciation_method` VARCHAR(64) NULL AFTER `current_book_value`,
  ADD COLUMN `depreciation_rate` DECIMAL(8,4) NULL AFTER `depreciation_method`,
  ADD COLUMN `depreciation_start_date` DATE NULL AFTER `depreciation_rate`,
  ADD COLUMN `useful_life_months` INT UNSIGNED NULL AFTER `depreciation_start_date`,
  ADD COLUMN `residual_value` DECIMAL(12,2) NULL AFTER `useful_life_months`,
  ADD COLUMN `gl_account` VARCHAR(64) NULL AFTER `residual_value`,
  ADD COLUMN `profit_center` VARCHAR(64) NULL AFTER `gl_account`,
  ADD COLUMN `asset_class` VARCHAR(64) NULL AFTER `profit_center`,

  ADD COLUMN `insurance_provider` VARCHAR(191) NULL AFTER `asset_class`,
  ADD COLUMN `insurance_policy_number` VARCHAR(100) NULL AFTER `insurance_provider`,
  ADD COLUMN `insurance_policy_type` VARCHAR(64) NULL AFTER `insurance_policy_number`,
  ADD COLUMN `insurance_start_date` DATE NULL AFTER `insurance_policy_type`,
  ADD COLUMN `insurance_expiry_date` DATE NULL AFTER `insurance_start_date`,
  ADD COLUMN `insurance_idv` DECIMAL(12,2) NULL AFTER `insurance_expiry_date`,
  ADD COLUMN `insurance_premium` DECIMAL(12,2) NULL AFTER `insurance_idv`,
  ADD COLUMN `insured_name` VARCHAR(191) NULL AFTER `insurance_premium`,
  ADD COLUMN `insurance_status` VARCHAR(64) NULL AFTER `insured_name`,
  ADD COLUMN `insurance_renewal_reminder` DATE NULL AFTER `insurance_status`,

  ADD COLUMN `warranty_provider` VARCHAR(191) NULL AFTER `warranty_months`,
  ADD COLUMN `warranty_start_date` DATE NULL AFTER `warranty_provider`,
  ADD COLUMN `warranty_end_date` DATE NULL AFTER `warranty_start_date`,
  ADD COLUMN `warranty_km` INT UNSIGNED NULL AFTER `warranty_end_date`,
  ADD COLUMN `current_odometer_km` INT UNSIGNED NULL AFTER `warranty_km`,
  ADD COLUMN `warranty_status` VARCHAR(64) NULL AFTER `current_odometer_km`,
  ADD COLUMN `has_battery_warranty` TINYINT(1) NOT NULL DEFAULT 0 AFTER `warranty_status`,
  ADD COLUMN `has_motor_warranty` TINYINT(1) NOT NULL DEFAULT 0 AFTER `has_battery_warranty`,
  ADD COLUMN `motor_warranty_end` DATE NULL AFTER `has_motor_warranty`;

ALTER TABLE `vehicles`
  ADD UNIQUE KEY `uk_vehicles_fleet_id` (`fleet_id`),
  ADD UNIQUE KEY `uk_vehicles_vin` (`vin`),
  ADD UNIQUE KEY `uk_vehicles_chassis` (`chassis_number`),
  ADD UNIQUE KEY `uk_vehicles_battery_serial` (`battery_serial_number`),
  ADD UNIQUE KEY `uk_vehicles_rfid` (`rfid_tag`),
  ADD UNIQUE KEY `uk_vehicles_barcode` (`barcode`),
  ADD KEY `idx_vehicles_company` (`company_id`),
  ADD KEY `idx_vehicles_entity` (`legal_entity_id`),
  ADD KEY `idx_vehicles_insurance_exp` (`insurance_expiry_date`),
  ADD KEY `idx_vehicles_reg_exp` (`registration_expiry`);

CREATE TABLE IF NOT EXISTS `vehicle_assignments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `vehicle_id` INT UNSIGNED NOT NULL,
  `assigned_to` INT UNSIGNED NULL,
  `assigned_type` VARCHAR(32) NULL COMMENT 'user | employee',
  `assignment_kind` VARCHAR(64) NULL COMMENT 'Employee | Driver | Fleet | Pool | …',
  `driver_name` VARCHAR(191) NULL,
  `driver_phone` VARCHAR(32) NULL,
  `employee_code` VARCHAR(64) NULL,
  `assignment_status` VARCHAR(64) NULL,
  `assignment_location` VARCHAR(100) NULL,
  `assigned_at` DATETIME NOT NULL,
  `expected_return_at` DATE NULL,
  `unassigned_at` DATETIME NULL,
  `assigned_by` INT UNSIGNED NULL,
  `unassigned_by` INT UNSIGNED NULL,
  `assign_note` TEXT NULL,
  `unassign_note` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `idx_va_vehicle` (`vehicle_id`),
  KEY `idx_va_open` (`vehicle_id`, `unassigned_at`),
  CONSTRAINT `fk_va_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_va_assigned_by` FOREIGN KEY (`assigned_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_va_unassigned_by` FOREIGN KEY (`unassigned_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Backfill fleet_id / barcode for existing rows (unique)
UPDATE `vehicles`
SET
  `fleet_id` = CONCAT('FLT-', `id`),
  `barcode` = CONCAT('BC-', `id`)
WHERE `fleet_id` IS NULL OR `barcode` IS NULL;
